src/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
        views.cart_add,
        name='cart_add'),
    path('remove/<int:product_id>/',
        views.cart_remove,
        name='cart_remove'),
]

src/main/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('shop.urls', namespace='shop')) 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list,
        name='product_list_by_category' 
        ),
    path('<int:id>/<slug:slug>', views.product_detail,
        name='product_detail')
]

src/cart/models.py
from django.db import models

# Create your models here.

src/shop/models.py
from tabnanny import verbose
from django.db import models
from django.urls import reverse


class  Category(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категорія'
        verbose_name_plural = 'Категорії'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])
    

class Product(models.Model):
    category = models.ForeignKey(Category, 
                                related_name='products', 
                                on_delete=models.CASCADE)
    
    name = models.CharField(max_length=150, db_index=True, verbose_name='Найменування')
    slug = models.CharField(max_length=150, db_index=True, unique=True, verbose_name='Ссилка')
    image = models.ImageField(upload_to='product/%Y/%m/%d', blank=True)
    description = models.TextField(max_length=1000, blank=True, verbose_name='Опис')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Ціна')
    available = models.BooleanField(default=True, verbose_name='Наявність')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Добавлений')
    uploaded = models.DateTimeField(auto_now=True, verbose_name='Зміненний')

    class Meta:
        ordering = ('name',)
        verbose_name = 'Товар'
        verbose_name_plural = 'Товари'
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

src/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
                                choices=PRODUCT_QUANTITY_CHOICES,
                                coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)            

src/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                                   'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

src/shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'shop/product/list.html',
                    {
                        'category': category,
                        'categories': categories,
                        'products': products
                    }
                    )

def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'shop/product/detail.html', {'product': product,
                                                        'cart_product_form': cart_product_form})

src/cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  Кошик
{% endblock %}

{% block content %}
  <h1>Кошик</h1>
  <table class="cart">
    <thead>
      <tr>
        <th>Картінка</th>
        <th>Товар</th>
        <th>Обновить кількість</th>
        <th>Удалить</th>
        <th>Кількість</th>
        <th>Ціна за шт</th>
        <th>Загальна вартість</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{{ product.get_absolute_url }}">
                <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
              </a>
            </td>
            <td>{{ product.name }}</td>
            <td>
              <form action="{% url 'cart:cart_add' product.id %}" method="post">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.update }}
                <input type="submit" value="Обновить">
                {% csrf_token %}
              </form>
            </td>
            <td><a href="{% url 'cart:cart_remove' product.id %}">Видалити</a></td>
            <td>
              {{ item.quantity }}
            </td>
            <td class="num">{{ item.price }} грн.</td>
            <td class="num">{{ item.total_price }} грн.</td>
          </tr>
        {% endwith %}
      {% endfor %}
      <tr class="total">
        <td>Всього</td>
        <td colspan="4"></td>
        <td class="num">{{ cart.get_total_price }} грн.</td>
      </tr>
    </tbody>
  </table>
  <p class="text-right">
    <a href="{% url 'shop:product_list' %}" class="button light">В магазин</a>
    <a href="#" class="button">Оформити замовлення</a>
  </p>
{% endblock %}

src/shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>{% block title %}Магазин АТЛАНТ{% endblock %}</title>
<link href="{% static "css/base.css" %}" rel="stylesheet">
</head>
<body>
<div id="header">
    <a href="/" class="logo"><img src="{% static "img/logo.jpg" %}"></a>
  <!--   <ul class="menu">
        <li><a href="/">Головна</a></li>
        <li><a href="#">Магазин</a></li>
        <li><a href="#">Готель</a></li>
    </ul>   -->  
</div>
<div id="subheader">    
    <div class="cart">
        {% with total_item=cart|length %}   
        {% if cart|length > 0 %}
        В кошику:
        <a href="{% url 'cart:cart_detail' %}">
            {{ total_item}} шт - {{ cart.get_total_price }} грн.
        </a>
        {% else %}
            Кошик пустий
        {% endif %}
        {% endwith %}
    </div>
</div>
<div id="content">
{% block content %}{% endblock %}
</div>
</body>
</html>

src/shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
{{ product.name }}
{% endblock %}
{% block content %}
<div class="product-detail">
<img src="{% if product.image %}{{ product.image.url }}{% else %}
{% static "img/no_image.png" %}{% endif %}">
<h1>{{ product.name }}</h1>
<h2>
<a href="{{ product.category.get_absolute_url }}">{{product.category }}</a>
</h2>
<p class="price">{{ product.price }} грн.</p>
    <form action="{% url 'cart:cart_add' product.id %}" method="post">
        {{ cart_product_form }}
        {% csrf_token %}
        <input type="submit" value="В кошик">
    </form>
{{ product.description|linebreaks }}
</div>
{% endblock %}

src/shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}
{% if category %}{{ category.name }}{% else %}Товари{% endif %}
{% block content %}
<div id="sidebar">
<h3>Категорія</h3>
<ul>
<li{% if not category  %}class="selected"{% endif %}>
<a href="{% url 'shop:product_list' %}">Всі товари</a>
</li>
{% for c in categories %}
<li {% if category.slug == c.slug %}class="selected" {% endif %}>
<a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
</li>
{% endfor %}
</ul>
</div>
<div id="main" class="product-list">
<h1>{% if category%}{{ category.name }}{% else %}Список всіх товарів{% endif %}</h1>
{% for product in products %}
<div class="item">
<a href="{{ product.get_absolute_url }}">
    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
</a>
<a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
<br>
{{ product.price }} грн.
</div>
{% endfor %}
</div>
{% endblock %}